[project]
protostar-version = "0.8.1"
lib-path = "lib"

[contracts]
main = ["src/main.cairo"]

ERC721_original = [
    "src/ERC721MintableBurnable.cairo",
]

["protostar.shared_command_configs"]
lib-path = "lib"
cairo-path = ["./lib/cairo_contracts/src", "./lib/cairopen_contracts/src"]

["protostar.contracts"]
ERC721_original = [
    "src/ERC721MintableBurnable.cairo",
]

[profile.devnet.protostar.deploy]
gateway-url="http://127.0.0.1:5050/"
chain-id="1"

[profile.testnet.protostar.deploy]
network="testnet"
